# Generated by Django 5.2.14 on 2026-05-07 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='explanation_en',
            field=models.TextField(blank=True, verbose_name='Izoh (EN)'),
        ),
        migrations.AddField(
            model_name='question',
            name='explanation_ru',
            field=models.TextField(blank=True, verbose_name='Izoh (RU)'),
        ),
    ]
