# Generated by Django 5.2.14 on 2026-05-07 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_question_explanation_en_question_explanation_ru'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='description_en',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='description_ru',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='title_en',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='title_ru',
        ),
        migrations.AlterField(
            model_name='quiz',
            name='description_uz',
            field=models.TextField(blank=True, verbose_name='Tavsif'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='title_uz',
            field=models.CharField(max_length=255, verbose_name='Sarlavha'),
        ),
    ]
