# Generated by Django 5.2.14 on 2026-05-07 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_remove_quiz_description_en_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choice',
            name='text_en',
        ),
        migrations.RemoveField(
            model_name='choice',
            name='text_ru',
        ),
        migrations.RemoveField(
            model_name='question',
            name='explanation_en',
        ),
        migrations.RemoveField(
            model_name='question',
            name='explanation_ru',
        ),
        migrations.RemoveField(
            model_name='question',
            name='text_en',
        ),
        migrations.RemoveField(
            model_name='question',
            name='text_ru',
        ),
        migrations.AlterField(
            model_name='choice',
            name='text_uz',
            field=models.CharField(max_length=500, verbose_name='Variant matni'),
        ),
        migrations.AlterField(
            model_name='question',
            name='explanation_uz',
            field=models.TextField(blank=True, verbose_name='Izoh'),
        ),
        migrations.AlterField(
            model_name='question',
            name='text_uz',
            field=models.TextField(verbose_name='Savol matni'),
        ),
    ]
