# Generated by Django 5.2.14 on 2026-05-08 09:25

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0006_usercreatedattempt'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_host', models.CharField(default='smtp.gmail.com', max_length=255, verbose_name='Email server (SMTP host)')),
                ('email_port', models.IntegerField(default=587, verbose_name='Port')),
                ('email_use_tls', models.BooleanField(default=True, verbose_name='TLS ishlatish')),
                ('email_use_ssl', models.BooleanField(default=False, verbose_name='SSL ishlatish')),
                ('email_host_user', models.EmailField(blank=True, max_length=254, verbose_name='Email manzili (login)')),
                ('email_host_password', models.CharField(blank=True, max_length=255, verbose_name='Email paroli (App Password)')),
                ('admin_email', models.EmailField(blank=True, max_length=254, verbose_name='Admin email manzili')),
                ('site_name', models.CharField(default='QuizHub', max_length=100, verbose_name='Sayt nomi')),
                ('site_url', models.URLField(blank=True, verbose_name='Sayt URL manzili')),
            ],
            options={
                'verbose_name': 'Sayt sozlamalari',
                'verbose_name_plural': 'Sayt sozlamalari',
            },
        ),
        migrations.AddField(
            model_name='usercreatedquiz',
            name='share_token',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Ulashish tokeni'),
        ),
        migrations.AlterField(
            model_name='usercreatedquiz',
            name='is_published',
            field=models.BooleanField(default=True, verbose_name='Ommaviy (Public)'),
        ),
        migrations.CreateModel(
            name='QuizUploadRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('quiz_title', models.CharField(max_length=255, verbose_name='Test nomi')),
                ('time_limit', models.PositiveIntegerField(default=30, verbose_name='Vaqt limiti (daqiqa)')),
                ('upload_file', models.FileField(upload_to='quiz_uploads/', verbose_name='Fayl')),
                ('note', models.TextField(blank=True, verbose_name='Izoh')),
                ('status', models.CharField(choices=[('pending', 'Kutilmoqda'), ('processing', "Ko'rib chiqilmoqda"), ('done', 'Bajarildi'), ('rejected', 'Rad etildi')], default='pending', max_length=20, verbose_name='Holati')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='quiz.category', verbose_name='Kategoriya')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi')),
            ],
            options={
                'verbose_name': "Quiz yuklash so'rovi",
                'verbose_name_plural': "Quiz yuklash so'rovlari",
                'ordering': ['-created_at'],
            },
        ),
    ]
