# Generated by Django 5.2.14 on 2026-05-08 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0007_sitesettings_usercreatedquiz_share_token_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='gemini_api_key',
            field=models.CharField(blank=True, help_text='Google AI Studio dan olingan API kalit. Fayl yuklashda AI tahlil uchun ishlatiladi.', max_length=255, verbose_name='Google Gemini API kaliti'),
        ),
    ]
